### ISSUE TITLE
关于老师实验室跟我在不同一校区的问题

### ISSUE THREAD

**Issue by BoZhiStudying233** [zimuzi2019/xducs-learning-tips#3]
学长好，想问一点科研的问题
我是机电工程学院的自动化专业的大二学生，之后希望去港校读研，目前有进老师项目组的想法。
现在已经有了一个不错的老师想要带我进组，但有点问题就是我在南校区，老师实验室在北校区，路程大约1h多一点。
老师说，如果我有决心的话，可以每周末来实验室。
想请教一下学长，我应该去这个老师的实验室，还是在南校区找一个也还不错的老师进组呢？

**Comment by zimuzi2019** [comment]
我本科没做过科研，可能给不了多少有效建议。而且信息比较少，没进组我也不知道老师能给你提供多少资源和指导

以及为啥非要过去，只要有按时组会监督一下进度就可以了吧，还是说组会是周末开？不是硬件方向去不去实验室有什么区别，不过如果是robotic那估计确实得去（

**Comment by BoZhiStudying233** [comment]
谢谢学长，因为我想到如果能进组在实验室有个工位的话，平时自习什么的也可以在那儿，但如果是北校区就没办法了QWQ。我打算先抽空去听一趟试试，谢谢
(的确是robotic的つ﹏⊂
